/**
 * QC Write API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SendTransactionRequest model module.
 * @module model/SendTransactionRequest
 * @version v1
 */
class SendTransactionRequest {
    /**
     * Constructs a new <code>SendTransactionRequest</code>.
     * @alias module:model/SendTransactionRequest
     */
    constructor() { 
        
        SendTransactionRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SendTransactionRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SendTransactionRequest} obj Optional instance to populate.
     * @return {module:model/SendTransactionRequest} The populated <code>SendTransactionRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SendTransactionRequest();

            if (data.hasOwnProperty('txnData')) {
                obj['txnData'] = ApiClient.convertToType(data['txnData'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>SendTransactionRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>SendTransactionRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['txnData'] && !(typeof data['txnData'] === 'string' || data['txnData'] instanceof String)) {
            throw new Error("Expected the field `txnData` to be a primitive type in the JSON string but got " + data['txnData']);
        }

        return true;
    }


}



/**
 * @member {String} txnData
 */
SendTransactionRequest.prototype['txnData'] = undefined;






export default SendTransactionRequest;

