/**
 * QC Write API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import ErrorResponseModel from '../model/ErrorResponseModel';
import SendTransactionRequest from '../model/SendTransactionRequest';
import TransactionSummaryResponse from '../model/TransactionSummaryResponse';

/**
* WriteApi service.
* @module api/WriteApiApi
* @version v1
*/
export default class WriteApiApi {

    /**
    * Constructs a new WriteApiApi. 
    * @alias module:api/WriteApiApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the sendTransaction operation.
     * @callback module:api/WriteApiApi~sendTransactionCallback
     * @param {String} error Error message, if any.
     * @param {module:model/TransactionSummaryResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Send Transaction
     * @param {Object} opts Optional parameters
     * @param {module:model/SendTransactionRequest} [sendTransactionRequest] 
     * @param {module:api/WriteApiApi~sendTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/TransactionSummaryResponse}
     */
    sendTransaction(opts, callback) {
      opts = opts || {};
      let postBody = opts['sendTransactionRequest'];

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = TransactionSummaryResponse;
      return this.apiClient.callApi(
        '/transactions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
